
package amar.webService.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://webService.amar/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns amar.webservice.Student
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService.amar/HelloWorld/getHelloWorldAsStringRequest", output = "http://webService.amar/HelloWorld/getHelloWorldAsStringResponse")
    public Student getHelloWorldAsString(
            @WebParam(name = "arg0", partName = "arg0")
            String arg0,
            @WebParam(name = "arg1", partName = "arg1")
            int arg1);

}
